---
title: "Answers to Frequently Asked Questions about RPIE"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### What is the Real Property Income and Expense Online Form?

Cook County Assessor Fritz Kaegi is happy to announce the launch of the **Real Property Income and Expense Online From** (RPIE, “R-pie”). This online tool will help gather data critical to the accurate and fair assessment of commercial properties in Cook County. This Online Filing tool is the CCAO's first online filing system for industrial and commercial property owners in Cook County. Any data submitted for one single business property contributes to the fair and accurate property assessment not just of that property, but of similar businesses throughout the county. 

We are publishing a functional tool for voluntary data collection to provide an opportunity for taxpayers and their representatives to provide feedback about how the Office can improve this filing system.

If your are unfamiliar with the Cook Count Assessor's RPIE Online Form, please read the FAQs **carefully.**

FAQs

**Is the RPIE Online Form mandatory for all properties?**

**No.** The RPIE Online Form is voluntary. The more businesses submit their information early in the year, the more accurate our assessments will be. You should encourage people to submit their RPIE form early because it will help us assess businesses in their community more accurately. Business can submit information throughout the year, but, again, earlier is better.

**Does filing the RPIE Online initiate an appeal?**  

**No.** An appeal can be initiated only by filing the [CCAO'S Appeal Form](https://www.cookcountyassessor.com/assets/forms/icappeal.pdf) with our Office. 

**Is the RPIE Online Form required to process an appeal?**

**Yes, if you are a supported property type.** A commercial appeal will not be processed if an RPIE was not filed with our office by the date appeals are due. Properties supported by the RPIE Online Form must submit their information through the Online Form. We will not accept paper RPIE submissions in lieu of using the RPIE Online Form. When the assessment calendar is finalized for 2020, we will link to that calendar here.

**What property types are supported by the RPIE Online Form?**

There are two types of properties that are currently supported by the RPIE Online Form. If the answer to either question below is 'yes', the property is likely supported by the RPIE Online Form.

*  Was the income from this PIN or property reported to the IRS on a Schedule E or Form 8825?
*  Is the lessee of this property party to a net, or triple net lease, and therfore responsible for taxes on that PIN?

Properties that are not supported by the RPIE Online Form can still file an RPIE filing in-person at our office. 

**What is the deadline for filing the RPIE Online Form?**

Since filing an RPIE is voluntary, there is no deadline for filing. However, The Cook County Assessor requires an RPIE submission in order to process an appeal on a commercial or industrial property. Therefore, if you intend to appeal a particular PIN, you should submit your RPIE filing before the appeal deadline for that PIN. The Cook County Assessor will not consider late RPIE filings on appeal. The Cook County Assessor will not accept printed RPIE forms in lieu of an online submission.

**What documents should I prepare to file**  

At minimum, you will need:

*   Each PIN <-> RPIE Code combination that was mailed to the owner of record.
*   Each Schedule E or Form 8825 associated with each PIN included in the filing.

You may also want to have:
*  Your rent roll, formatted for the RPIE. You can download our commercial template here and our residential template here.
*  Information about the building's addresses.
*  The percentage of the building associated with each of your PINs.

For lessees responsible for taxes, please have:

*  Your lease requiring you to pay property taxes.
Can we change this to 
**I lost my RPIE code! I need to edit a submitted filing! I need help (with the RPIE form)!**  

If you need support completing your RPIE submission, managing your account, or managing past submissions, please call our office at (312) 443-7550 or email us at RPIEsupport@cookcountyassessor.com.

**Does the filing have to be completed by the property owner themselves?**

**No.** This online tool is designed to support owners, lessees responsible for property taxes, and their representatives who are filing for one or mulitple business entities. You can even start a filing and then transfer the filing duties to another party.

**How many RPIE filings should I submit?**

There should be a 1-to-1 correspondence between your IRS Schedule E/Form 8825, and/or net or triple net lease. For example, a large company that owns multiple apartment buildings should file a single RPIE filing that includes all the properties they own. If one individual owns multiple properties, and filed two IRS tax returns with two Schedule Es attached, they should submit two RPIE filings.

**Will my data be saved to make future filings easier?**

**Yes!** We have designed this form so that most of the data input in a given year will carry over to the next year for each PIN. 

**If I do not file an RPIE, what are the consequences?**  

There are no legal consequences for failing or refusing to file an RPIE. For those filing for the purpose of a property valuation appeal, per the Official Rules of the Cook County Assessor, not completing the RPIE form (using the PDF or online tool) is grounds for an appeal decision of "No Change." Property owners and their filing representatives who cannot use the RPIE Online Form can use the RPIE PDF forms.

**How will the submitted data be used?**  

This data will be aggregated and anonymized, and combined with other data sets to produce internal diagnostic reports. These aggregated reports will provide The Assessor and his Dputies and Directors with information about the integrity of the assessment, the accuracy of assessments, appeals results, RPIE Onling Form participation rates, and other matters directly related to the valuation of income-producing properties, alongside other data sources used by the CCAO.   
Data submitted during the beta testing phase will not be used for property valuation appeals. Data submitted after our beta testing phase that is associated with a PIN will also be used by analysts processing an appeal associated with that PIN.

**Is my data private? Safe?**  

The CCAO will limit the risk re-identification of anonymized data through reasonable means.The goal of these methods is that any data published could not be used to identify a single business entity. Data used internally will be anonymized and limited in size to prevent accidental disclosure of private information. Read more in our Privacy Policy.

<!-- To read more about SB 1379, click here. -->
